import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import IcSharpDiamond from '~icons/ic/sharp-diamond'
import IconParkSolidLike from '~icons/icon-park-solid/like'
import MdiComment from '~icons/mdi/comment'
import Navbar from '../components/navbar'
import PostImage from '../components/post-image'
import RecommendedAuthors from '../components/recommended-authors'
import styles from '../styles/Home.module.css'
import { getPosts } from './api/post'

interface Post {
  id: string
  title: string
  profile_link: string
  img_source: string
  abstract: string
  diamond_count: number
  nickname: string
  comment_count: number
  like_count: number
}

interface HomeProps {
  posts: Post[]
}

const Home: NextPage<HomeProps> = (props) => {
  const { posts } = props
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className={styles.main}>
        <div className={styles['post-container']}>
          <ul className={styles['post-list']}>
            {posts.map((p) => {
              const {
                id,
                title,
                profile_link,
                img_source,
                abstract,
                diamond_count,
                nickname,
                comment_count,
                like_count,
              } = p
              return (
                <li className={styles.post} key={id}>
                  <div className={styles['post-content']}>
                    <Link
                      className={styles['post-title']}
                      target="_blank"
                      href={profile_link}
                    >
                      {title}
                    </Link>
                    <div className={styles['post-abstract']}>{abstract}</div>
                    <div className={styles['post-meta']}>
                      <span className={styles.diamond}>
                        <IcSharpDiamond />
                        <span>{diamond_count}</span>
                      </span>
                      <span className={styles.nickname}>
                        <span>{nickname}</span>
                      </span>
                      <span className={styles.comment}>
                        <MdiComment />
                        <span>{comment_count}</span>
                      </span>
                      <span className={styles.like}>
                        <IconParkSolidLike />
                        <span>{like_count}</span>
                      </span>
                    </div>
                  </div>
                  {img_source && (
                    <div className={styles['post-img']}>
                      <Link href={profile_link} target="_blank" passHref>
                        <PostImage
                          className="img-blur-done"
                          src={img_source}
                          alt="120"
                          width={150}
                          height={100}
                        />
                      </Link>
                    </div>
                  )}
                </li>
              )
            })}
          </ul>
        </div>
        <aside className={styles.sidebar}>
          <RecommendedAuthors />
        </aside>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { posts } = await getPosts({ pageNum: 1 })
  console.log('Get post success'+ '\n', JSON.stringify(posts))

  // will be passed to the page component as props
  return {
    props: {
      posts: JSON.parse(JSON.stringify(posts)),
    },
  }
}

export default Home
